#[derive(Clone, Copy)]
pub struct Floss<'a> {
    number: &'a str,
    name: &'a str,
    pub red: u8,
    pub green: u8,
    pub blue: u8,
}

pub fn get_dmc_floss() -> Vec<Floss<'static>> {
    vec![
        Floss {
            number: "3713",
            name: "Salmon Very Light",
            red: 255,
            green: 226,
            blue: 226,
        },
        Floss {
            number: "761",
            name: "Salmon Light",
            red: 255,
            green: 201,
            blue: 201,
        },
        Floss {
            number: "760",
            name: "Salmon",
            red: 245,
            green: 173,
            blue: 173,
        },
        Floss {
            number: "3712",
            name: "Salmon Medium",
            red: 241,
            green: 135,
            blue: 135,
        },
        Floss {
            number: "3328",
            name: "Salmon Dark",
            red: 227,
            green: 109,
            blue: 109,
        },
        Floss {
            number: "347",
            name: "Salmon Very Dark",
            red: 191,
            green: 45,
            blue: 45,
        },
        Floss {
            number: "353",
            name: "Peach",
            red: 254,
            green: 215,
            blue: 204,
        },
        Floss {
            number: "352",
            name: "Coral Light",
            red: 253,
            green: 156,
            blue: 151,
        },
        Floss {
            number: "351",
            name: "Coral",
            red: 233,
            green: 106,
            blue: 103,
        },
        Floss {
            number: "350",
            name: "Coral Medium",
            red: 224,
            green: 72,
            blue: 72,
        },
        Floss {
            number: "349",
            name: "Coral Dark",
            red: 210,
            green: 16,
            blue: 53,
        },
        Floss {
            number: "817",
            name: "Coral Red Very Dark",
            red: 187,
            green: 5,
            blue: 31,
        },
        Floss {
            number: "3708",
            name: "Melon Light",
            red: 255,
            green: 203,
            blue: 213,
        },
        Floss {
            number: "3706",
            name: "Melon Medium",
            red: 255,
            green: 173,
            blue: 188,
        },
        Floss {
            number: "3705",
            name: "Melon Dark",
            red: 255,
            green: 121,
            blue: 146,
        },
        Floss {
            number: "3801",
            name: "Melon Very Dark",
            red: 231,
            green: 73,
            blue: 103,
        },
        Floss {
            number: "666",
            name: "Bright Red",
            red: 227,
            green: 29,
            blue: 66,
        },
        Floss {
            number: "321",
            name: "Red",
            red: 199,
            green: 43,
            blue: 59,
        },
        Floss {
            number: "304",
            name: "Red Medium",
            red: 183,
            green: 31,
            blue: 51,
        },
        Floss {
            number: "498",
            name: "Red Dark",
            red: 167,
            green: 19,
            blue: 43,
        },
        Floss {
            number: "816",
            name: "Garnet",
            red: 151,
            green: 11,
            blue: 35,
        },
        Floss {
            number: "815",
            name: "Garnet Medium",
            red: 135,
            green: 7,
            blue: 31,
        },
        Floss {
            number: "814",
            name: "Garnet Dark",
            red: 123,
            green: 0,
            blue: 27,
        },
        Floss {
            number: "894",
            name: "Carnation Very Light",
            red: 255,
            green: 178,
            blue: 187,
        },
        Floss {
            number: "893",
            name: "Carnation Light",
            red: 252,
            green: 144,
            blue: 162,
        },
        Floss {
            number: "892",
            name: "Carnation Medium",
            red: 255,
            green: 121,
            blue: 140,
        },
        Floss {
            number: "891",
            name: "Carnation Dark",
            red: 255,
            green: 87,
            blue: 115,
        },
        Floss {
            number: "818",
            name: "Baby Pink",
            red: 255,
            green: 223,
            blue: 217,
        },
        Floss {
            number: "957",
            name: "Geranium Pale",
            red: 253,
            green: 181,
            blue: 181,
        },
        Floss {
            number: "956",
            name: "Geranium",
            red: 255,
            green: 145,
            blue: 145,
        },
        Floss {
            number: "309",
            name: "Rose Dark",
            red: 86,
            green: 74,
            blue: 74,
        },
        Floss {
            number: "963",
            name: "Dusty Rose Ult Vy Lt",
            red: 255,
            green: 215,
            blue: 215,
        },
        Floss {
            number: "3716",
            name: "Dusty Rose Med Vy Lt",
            red: 255,
            green: 189,
            blue: 189,
        },
        Floss {
            number: "962",
            name: "Dusty Rose Medium",
            red: 230,
            green: 138,
            blue: 138,
        },
        Floss {
            number: "961",
            name: "Dusty Rose Dark",
            red: 207,
            green: 115,
            blue: 115,
        },
        Floss {
            number: "3833",
            name: "Raspberry Light",
            red: 234,
            green: 134,
            blue: 153,
        },
        Floss {
            number: "3832",
            name: "Raspberry Medium",
            red: 219,
            green: 85,
            blue: 110,
        },
        Floss {
            number: "3831",
            name: "Raspberry Dark",
            red: 179,
            green: 47,
            blue: 72,
        },
        Floss {
            number: "777",
            name: "Raspberry Very Dark",
            red: 145,
            green: 53,
            blue: 70,
        },
        Floss {
            number: "819",
            name: "Baby Pink Light",
            red: 255,
            green: 238,
            blue: 235,
        },
        Floss {
            number: "3326",
            name: "Rose Light",
            red: 251,
            green: 173,
            blue: 180,
        },
        Floss {
            number: "776",
            name: "Pink Medium",
            red: 252,
            green: 176,
            blue: 185,
        },
        Floss {
            number: "899",
            name: "Rose Medium",
            red: 242,
            green: 118,
            blue: 136,
        },
        Floss {
            number: "335",
            name: "Rose",
            red: 238,
            green: 84,
            blue: 110,
        },
        Floss {
            number: "326",
            name: "Rose Very Dark",
            red: 179,
            green: 59,
            blue: 75,
        },
        Floss {
            number: "151",
            name: "Dusty Rose Vry Lt",
            red: 240,
            green: 206,
            blue: 212,
        },
        Floss {
            number: "3354",
            name: "Dusty Rose Light",
            red: 228,
            green: 166,
            blue: 172,
        },
        Floss {
            number: "3733",
            name: "Dusty Rose",
            red: 232,
            green: 135,
            blue: 155,
        },
        Floss {
            number: "3731",
            name: "Dusty Rose Very Dark",
            red: 218,
            green: 103,
            blue: 131,
        },
        Floss {
            number: "3350",
            name: "Dusty Rose Ultra Dark",
            red: 188,
            green: 67,
            blue: 101,
        },
        Floss {
            number: "150",
            name: "Dusty Rose Ult Vy Dk",
            red: 171,
            green: 2,
            blue: 73,
        },
        Floss {
            number: "3689",
            name: "Mauve Light",
            red: 251,
            green: 191,
            blue: 194,
        },
        Floss {
            number: "3688",
            name: "Mauve Medium",
            red: 231,
            green: 169,
            blue: 172,
        },
        Floss {
            number: "3687",
            name: "Mauve",
            red: 201,
            green: 107,
            blue: 112,
        },
        Floss {
            number: "3803",
            name: "Mauve Dark",
            red: 171,
            green: 51,
            blue: 87,
        },
        Floss {
            number: "3685",
            name: "Mauve Very Dark",
            red: 136,
            green: 21,
            blue: 49,
        },
        Floss {
            number: "605",
            name: "Cranberry Very Light",
            red: 255,
            green: 192,
            blue: 205,
        },
        Floss {
            number: "604",
            name: "Cranberry Light",
            red: 255,
            green: 176,
            blue: 190,
        },
        Floss {
            number: "603",
            name: "Cranberry",
            red: 255,
            green: 164,
            blue: 190,
        },
        Floss {
            number: "602",
            name: "Cranberry Medium",
            red: 226,
            green: 72,
            blue: 116,
        },
        Floss {
            number: "601",
            name: "Cranberry Dark",
            red: 209,
            green: 40,
            blue: 106,
        },
        Floss {
            number: "600",
            name: "Cranberry Very Dark",
            red: 205,
            green: 47,
            blue: 99,
        },
        Floss {
            number: "3806",
            name: "Cyclamen Pink Light",
            red: 255,
            green: 140,
            blue: 174,
        },
        Floss {
            number: "3805",
            name: "Cyclamen Pink",
            red: 243,
            green: 71,
            blue: 139,
        },
        Floss {
            number: "3804",
            name: "Cyclamen Pink Dark",
            red: 224,
            green: 40,
            blue: 118,
        },
        Floss {
            number: "3609",
            name: "Plum Ultra Light",
            red: 244,
            green: 174,
            blue: 213,
        },
        Floss {
            number: "3608",
            name: "Plum Very Light",
            red: 234,
            green: 156,
            blue: 196,
        },
        Floss {
            number: "3607",
            name: "Plum Light",
            red: 197,
            green: 73,
            blue: 137,
        },
        Floss {
            number: "718",
            name: "Plum",
            red: 156,
            green: 36,
            blue: 98,
        },
        Floss {
            number: "917",
            name: "Plum Medium",
            red: 155,
            green: 19,
            blue: 89,
        },
        Floss {
            number: "915",
            name: "Plum Dark",
            red: 130,
            green: 0,
            blue: 67,
        },
        Floss {
            number: "225",
            name: "Shell Pink Ult Vy Lt",
            red: 255,
            green: 223,
            blue: 213,
        },
        Floss {
            number: "224",
            name: "Shell Pink Very Light",
            red: 235,
            green: 183,
            blue: 175,
        },
        Floss {
            number: "152",
            name: "Shell Pink Med Light",
            red: 226,
            green: 160,
            blue: 153,
        },
        Floss {
            number: "223",
            name: "Shell Pink Light",
            red: 204,
            green: 132,
            blue: 124,
        },
        Floss {
            number: "3722",
            name: "Shell Pink Med",
            red: 188,
            green: 108,
            blue: 100,
        },
        Floss {
            number: "3721",
            name: "Shell Pink Dark",
            red: 161,
            green: 75,
            blue: 81,
        },
        Floss {
            number: "221",
            name: "Shell Pink Vy Dk",
            red: 136,
            green: 62,
            blue: 67,
        },
        Floss {
            number: "778",
            name: "Antique Mauve Vy Lt",
            red: 223,
            green: 179,
            blue: 187,
        },
        Floss {
            number: "3727",
            name: "Antique Mauve Light",
            red: 219,
            green: 169,
            blue: 178,
        },
        Floss {
            number: "316",
            name: "Antique Mauve Med",
            red: 183,
            green: 115,
            blue: 127,
        },
        Floss {
            number: "3726",
            name: "Antique Mauve Dark",
            red: 155,
            green: 91,
            blue: 102,
        },
        Floss {
            number: "315",
            name: "Antique Mauve Md Dk",
            red: 129,
            green: 73,
            blue: 82,
        },
        Floss {
            number: "3802",
            name: "Antique Mauve Vy Dk",
            red: 113,
            green: 65,
            blue: 73,
        },
        Floss {
            number: "902",
            name: "Garnet Very Dark",
            red: 130,
            green: 38,
            blue: 55,
        },
        Floss {
            number: "3743",
            name: "Antique Violet Vy Lt",
            red: 215,
            green: 203,
            blue: 211,
        },
        Floss {
            number: "3042",
            name: "Antique Violet Light",
            red: 183,
            green: 157,
            blue: 167,
        },
        Floss {
            number: "3041",
            name: "Antique Violet Medium",
            red: 149,
            green: 111,
            blue: 124,
        },
        Floss {
            number: "3740",
            name: "Antique Violet Dark",
            red: 120,
            green: 87,
            blue: 98,
        },
        Floss {
            number: "3836",
            name: "Grape Light",
            red: 186,
            green: 145,
            blue: 170,
        },
        Floss {
            number: "3835",
            name: "Grape Medium",
            red: 148,
            green: 96,
            blue: 131,
        },
        Floss {
            number: "3834",
            name: "Grape Dark",
            red: 114,
            green: 55,
            blue: 93,
        },
        Floss {
            number: "154",
            name: "Grape Very Dark",
            red: 87,
            green: 36,
            blue: 51,
        },
        Floss {
            number: "211",
            name: "Lavender Light",
            red: 227,
            green: 203,
            blue: 227,
        },
        Floss {
            number: "210",
            name: "Lavender Medium",
            red: 195,
            green: 159,
            blue: 195,
        },
        Floss {
            number: "209",
            name: "Lavender Dark",
            red: 163,
            green: 123,
            blue: 167,
        },
        Floss {
            number: "208",
            name: "Lavender Very Dark",
            red: 131,
            green: 91,
            blue: 139,
        },
        Floss {
            number: "3837",
            name: "Lavender Ultra Dark",
            red: 108,
            green: 58,
            blue: 110,
        },
        Floss {
            number: "327",
            name: "Violet Dark",
            red: 99,
            green: 54,
            blue: 102,
        },
        Floss {
            number: "153",
            name: "Violet Very Light",
            red: 230,
            green: 204,
            blue: 217,
        },
        Floss {
            number: "554",
            name: "Violet Light",
            red: 219,
            green: 179,
            blue: 203,
        },
        Floss {
            number: "553",
            name: "Violet",
            red: 163,
            green: 99,
            blue: 139,
        },
        Floss {
            number: "552",
            name: "Violet  Medium",
            red: 128,
            green: 58,
            blue: 107,
        },
        Floss {
            number: "550",
            name: "Violet Very Dark",
            red: 92,
            green: 24,
            blue: 78,
        },
        Floss {
            number: "3747",
            name: "Blue Violet Vy Lt",
            red: 211,
            green: 215,
            blue: 237,
        },
        Floss {
            number: "341",
            name: "Blue Violet Light",
            red: 183,
            green: 191,
            blue: 221,
        },
        Floss {
            number: "156",
            name: "Blue Violet Med Lt",
            red: 163,
            green: 174,
            blue: 209,
        },
        Floss {
            number: "340",
            name: "Blue Violet Medium",
            red: 173,
            green: 167,
            blue: 199,
        },
        Floss {
            number: "155",
            name: "Blue Violet Med Dark",
            red: 152,
            green: 145,
            blue: 182,
        },
        Floss {
            number: "3746",
            name: "Blue Violet Dark",
            red: 119,
            green: 107,
            blue: 152,
        },
        Floss {
            number: "333",
            name: "Blue Violet Very Dark",
            red: 92,
            green: 84,
            blue: 120,
        },
        Floss {
            number: "157",
            name: "Cornflower Blue Vy Lt",
            red: 187,
            green: 195,
            blue: 217,
        },
        Floss {
            number: "794",
            name: "Cornflower Blue Light",
            red: 143,
            green: 156,
            blue: 193,
        },
        Floss {
            number: "793",
            name: "Cornflower Blue Med",
            red: 112,
            green: 125,
            blue: 162,
        },
        Floss {
            number: "3807",
            name: "Cornflower Blue",
            red: 96,
            green: 103,
            blue: 140,
        },
        Floss {
            number: "792",
            name: "Cornflower Blue Dark",
            red: 85,
            green: 91,
            blue: 123,
        },
        Floss {
            number: "158",
            name: "Cornflower Blu M V D",
            red: 76,
            green: 82,
            blue: 110,
        },
        Floss {
            number: "791",
            name: "Cornflower Blue V D",
            red: 70,
            green: 69,
            blue: 99,
        },
        Floss {
            number: "3840",
            name: "Lavender Blue Light",
            red: 176,
            green: 192,
            blue: 218,
        },
        Floss {
            number: "3839",
            name: "Lavender Blue Med",
            red: 123,
            green: 142,
            blue: 171,
        },
        Floss {
            number: "3838",
            name: "Lavender Blue Dark",
            red: 92,
            green: 114,
            blue: 148,
        },
        Floss {
            number: "800",
            name: "Delft Blue Pale",
            red: 192,
            green: 204,
            blue: 222,
        },
        Floss {
            number: "809",
            name: "Delft Blue",
            red: 148,
            green: 168,
            blue: 198,
        },
        Floss {
            number: "799",
            name: "Delft Blue Medium",
            red: 116,
            green: 142,
            blue: 182,
        },
        Floss {
            number: "798",
            name: "Delft Blue Dark",
            red: 70,
            green: 106,
            blue: 142,
        },
        Floss {
            number: "797",
            name: "Royal Blue",
            red: 19,
            green: 71,
            blue: 125,
        },
        Floss {
            number: "796",
            name: "Royal Blue Dark",
            red: 17,
            green: 65,
            blue: 109,
        },
        Floss {
            number: "820",
            name: "Royal Blue Very Dark",
            red: 14,
            green: 54,
            blue: 92,
        },
        Floss {
            number: "162",
            name: "Blue Ultra Very Light",
            red: 219,
            green: 236,
            blue: 245,
        },
        Floss {
            number: "827",
            name: "Blue Very Light",
            red: 189,
            green: 221,
            blue: 237,
        },
        Floss {
            number: "813",
            name: "Blue Light",
            red: 161,
            green: 194,
            blue: 215,
        },
        Floss {
            number: "826",
            name: "Blue Medium",
            red: 107,
            green: 158,
            blue: 191,
        },
        Floss {
            number: "825",
            name: "Blue Dark",
            red: 71,
            green: 129,
            blue: 165,
        },
        Floss {
            number: "824",
            name: "Blue Very Dark",
            red: 57,
            green: 105,
            blue: 135,
        },
        Floss {
            number: "996",
            name: "Electric Blue Medium",
            red: 48,
            green: 194,
            blue: 236,
        },
        Floss {
            number: "3843",
            name: "Electric Blue",
            red: 20,
            green: 170,
            blue: 208,
        },
        Floss {
            number: "995",
            name: "Electric Blue Dark",
            red: 38,
            green: 150,
            blue: 182,
        },
        Floss {
            number: "3846",
            name: "Turquoise Bright Light",
            red: 6,
            green: 227,
            blue: 230,
        },
        Floss {
            number: "3845",
            name: "Turquoise Bright Med",
            red: 4,
            green: 196,
            blue: 202,
        },
        Floss {
            number: "3844",
            name: "Turquoise Bright Dark",
            red: 18,
            green: 174,
            blue: 186,
        },
        Floss {
            number: "159",
            name: "Blue Gray Light",
            red: 199,
            green: 202,
            blue: 215,
        },
        Floss {
            number: "160",
            name: "Blue Gray Medium",
            red: 153,
            green: 159,
            blue: 183,
        },
        Floss {
            number: "161",
            name: "Blue Gray",
            red: 120,
            green: 128,
            blue: 164,
        },
        Floss {
            number: "3756",
            name: "Baby Blue Ult Vy Lt",
            red: 238,
            green: 252,
            blue: 252,
        },
        Floss {
            number: "775",
            name: "Baby Blue Very Light",
            red: 217,
            green: 235,
            blue: 241,
        },
        Floss {
            number: "3841",
            name: "Baby Blue Pale",
            red: 205,
            green: 223,
            blue: 237,
        },
        Floss {
            number: "3325",
            name: "Baby Blue Light",
            red: 184,
            green: 210,
            blue: 230,
        },
        Floss {
            number: "3755",
            name: "Baby Blue",
            red: 147,
            green: 180,
            blue: 206,
        },
        Floss {
            number: "334",
            name: "Baby Blue Medium",
            red: 115,
            green: 159,
            blue: 193,
        },
        Floss {
            number: "322",
            name: "Baby Blue Dark",
            red: 90,
            green: 143,
            blue: 184,
        },
        Floss {
            number: "312",
            name: "Baby Blue Very Dark",
            red: 53,
            green: 102,
            blue: 139,
        },
        Floss {
            number: "803",
            name: "Baby Blue Ult Vy Dk",
            red: 44,
            green: 89,
            blue: 124,
        },
        Floss {
            number: "336",
            name: "Navy Blue",
            red: 37,
            green: 59,
            blue: 115,
        },
        Floss {
            number: "823",
            name: "Navy Blue Dark",
            red: 33,
            green: 48,
            blue: 99,
        },
        Floss {
            number: "939",
            name: "Navy Blue Very Dark",
            red: 27,
            green: 40,
            blue: 83,
        },
        Floss {
            number: "3753",
            name: "Antique Blue Ult Vy Lt",
            red: 219,
            green: 226,
            blue: 233,
        },
        Floss {
            number: "3752",
            name: "Antique Blue Very Lt",
            red: 199,
            green: 209,
            blue: 219,
        },
        Floss {
            number: "932",
            name: "Antique Blue Light",
            red: 162,
            green: 181,
            blue: 198,
        },
        Floss {
            number: "931",
            name: "Antique Blue Medium",
            red: 106,
            green: 133,
            blue: 158,
        },
        Floss {
            number: "930",
            name: "Antique Blue Dark",
            red: 69,
            green: 92,
            blue: 113,
        },
        Floss {
            number: "3750",
            name: "Antique Blue Very Dk",
            red: 56,
            green: 76,
            blue: 94,
        },
        Floss {
            number: "828",
            name: "Sky Blue Vy Lt",
            red: 197,
            green: 232,
            blue: 237,
        },
        Floss {
            number: "3761",
            name: "Sky Blue Light",
            red: 172,
            green: 216,
            blue: 226,
        },
        Floss {
            number: "519",
            name: "Sky Blue",
            red: 126,
            green: 177,
            blue: 200,
        },
        Floss {
            number: "518",
            name: "Wedgewood Light",
            red: 79,
            green: 147,
            blue: 167,
        },
        Floss {
            number: "3760",
            name: "Wedgewood Med",
            red: 62,
            green: 133,
            blue: 162,
        },
        Floss {
            number: "517",
            name: "Wedgewood Dark",
            red: 59,
            green: 118,
            blue: 143,
        },
        Floss {
            number: "3842",
            name: "Wedgewood Vry Dk",
            red: 50,
            green: 102,
            blue: 124,
        },
        Floss {
            number: "311",
            name: "Wedgewood Ult VyDk",
            red: 28,
            green: 80,
            blue: 102,
        },
        Floss {
            number: "747",
            name: "Peacock Blue Vy Lt",
            red: 229,
            green: 252,
            blue: 253,
        },
        Floss {
            number: "3766",
            name: "Peacock Blue Light",
            red: 153,
            green: 207,
            blue: 217,
        },
        Floss {
            number: "807",
            name: "Peacock Blue",
            red: 100,
            green: 171,
            blue: 186,
        },
        Floss {
            number: "806",
            name: "Peacock Blue Dark",
            red: 61,
            green: 149,
            blue: 165,
        },
        Floss {
            number: "3765",
            name: "Peacock Blue Vy Dk",
            red: 52,
            green: 127,
            blue: 140,
        },
        Floss {
            number: "3811",
            name: "Turquoise Very Light",
            red: 188,
            green: 227,
            blue: 230,
        },
        Floss {
            number: "598",
            name: "Turquoise Light",
            red: 144,
            green: 195,
            blue: 204,
        },
        Floss {
            number: "597",
            name: "Turquoise",
            red: 91,
            green: 163,
            blue: 179,
        },
        Floss {
            number: "3810",
            name: "Turquoise Dark",
            red: 72,
            green: 142,
            blue: 154,
        },
        Floss {
            number: "3809",
            name: "Turquoise Vy Dark",
            red: 63,
            green: 124,
            blue: 133,
        },
        Floss {
            number: "3808",
            name: "Turquoise Ult Vy Dk",
            red: 54,
            green: 105,
            blue: 112,
        },
        Floss {
            number: "928",
            name: "Gray Green Vy Lt",
            red: 221,
            green: 227,
            blue: 227,
        },
        Floss {
            number: "927",
            name: "Gray Green Light",
            red: 189,
            green: 203,
            blue: 203,
        },
        Floss {
            number: "926",
            name: "Gray Green Med",
            red: 152,
            green: 174,
            blue: 174,
        },
        Floss {
            number: "3768",
            name: "Gray Green Dark",
            red: 101,
            green: 127,
            blue: 127,
        },
        Floss {
            number: "924",
            name: "Gray Green Vy Dark",
            red: 86,
            green: 106,
            blue: 106,
        },
        Floss {
            number: "3849",
            name: "Teal Green Light",
            red: 82,
            green: 179,
            blue: 164,
        },
        Floss {
            number: "3848",
            name: "Teal Green Med",
            red: 85,
            green: 147,
            blue: 146,
        },
        Floss {
            number: "3847",
            name: "Teal Green Dark",
            red: 52,
            green: 125,
            blue: 117,
        },
        Floss {
            number: "964",
            name: "Sea Green Light",
            red: 169,
            green: 226,
            blue: 216,
        },
        Floss {
            number: "959",
            name: "Sea Green Med",
            red: 89,
            green: 199,
            blue: 180,
        },
        Floss {
            number: "958",
            name: "Sea Green Dark",
            red: 62,
            green: 182,
            blue: 161,
        },
        Floss {
            number: "3812",
            name: "Sea Green Vy Dk",
            red: 47,
            green: 140,
            blue: 132,
        },
        Floss {
            number: "3851",
            name: "Green Bright Lt",
            red: 73,
            green: 179,
            blue: 161,
        },
        Floss {
            number: "943",
            name: "Green Bright Md",
            red: 61,
            green: 147,
            blue: 132,
        },
        Floss {
            number: "3850",
            name: "Green Bright Dk",
            red: 55,
            green: 132,
            blue: 119,
        },
        Floss {
            number: "993",
            name: "Aquamarine Vy Lt",
            red: 144,
            green: 192,
            blue: 180,
        },
        Floss {
            number: "992",
            name: "Aquamarine Lt",
            red: 111,
            green: 174,
            blue: 159,
        },
        Floss {
            number: "3814",
            name: "Aquamarine",
            red: 80,
            green: 139,
            blue: 125,
        },
        Floss {
            number: "991",
            name: "Aquamarine Dk",
            red: 71,
            green: 123,
            blue: 110,
        },
        Floss {
            number: "966",
            name: "Jade Ultra Vy Lt",
            red: 185,
            green: 215,
            blue: 192,
        },
        Floss {
            number: "564",
            name: "Jade Very Light",
            red: 167,
            green: 205,
            blue: 175,
        },
        Floss {
            number: "563",
            name: "Jade Light",
            red: 143,
            green: 192,
            blue: 152,
        },
        Floss {
            number: "562",
            name: "Jade Medium",
            red: 83,
            green: 151,
            blue: 106,
        },
        Floss {
            number: "505",
            name: "Jade Green",
            red: 51,
            green: 131,
            blue: 98,
        },
        Floss {
            number: "3817",
            name: "Celadon Green Lt",
            red: 153,
            green: 195,
            blue: 170,
        },
        Floss {
            number: "3816",
            name: "Celadon Green",
            red: 101,
            green: 165,
            blue: 125,
        },
        Floss {
            number: "163",
            name: "Celadon Green Md",
            red: 77,
            green: 131,
            blue: 97,
        },
        Floss {
            number: "3815",
            name: "Celadon Green Dk",
            red: 71,
            green: 119,
            blue: 89,
        },
        Floss {
            number: "561",
            name: "Celadon Green VD",
            red: 44,
            green: 106,
            blue: 69,
        },
        Floss {
            number: "504",
            name: "Blue Green Vy Lt",
            red: 196,
            green: 222,
            blue: 204,
        },
        Floss {
            number: "3813",
            name: "Blue Green Lt",
            red: 178,
            green: 212,
            blue: 189,
        },
        Floss {
            number: "503",
            name: "Blue Green Med",
            red: 123,
            green: 172,
            blue: 148,
        },
        Floss {
            number: "502",
            name: "Blue Green",
            red: 91,
            green: 144,
            blue: 113,
        },
        Floss {
            number: "501",
            name: "Blue Green Dark",
            red: 57,
            green: 111,
            blue: 82,
        },
        Floss {
            number: "500",
            name: "Blue Green Vy Dk",
            red: 4,
            green: 77,
            blue: 51,
        },
        Floss {
            number: "955",
            name: "Nile Green Light",
            red: 162,
            green: 214,
            blue: 173,
        },
        Floss {
            number: "954",
            name: "Nile Green",
            red: 136,
            green: 186,
            blue: 145,
        },
        Floss {
            number: "913",
            name: "Nile Green Med",
            red: 109,
            green: 171,
            blue: 119,
        },
        Floss {
            number: "912",
            name: "Emerald Green Lt",
            red: 27,
            green: 157,
            blue: 107,
        },
        Floss {
            number: "911",
            name: "Emerald Green Med",
            red: 24,
            green: 144,
            blue: 101,
        },
        Floss {
            number: "910",
            name: "Emerald Green Dark",
            red: 24,
            green: 126,
            blue: 86,
        },
        Floss {
            number: "909",
            name: "Emerald Green Vy Dk",
            red: 21,
            green: 111,
            blue: 73,
        },
        Floss {
            number: "3818",
            name: "Emerald Grn Ult V Dk",
            red: 17,
            green: 90,
            blue: 59,
        },
        Floss {
            number: "369",
            name: "Pistachio Green Vy Lt",
            red: 215,
            green: 237,
            blue: 204,
        },
        Floss {
            number: "368",
            name: "Pistachio Green Lt",
            red: 166,
            green: 194,
            blue: 152,
        },
        Floss {
            number: "320",
            name: "Pistachio Green Med",
            red: 105,
            green: 136,
            blue: 90,
        },
        Floss {
            number: "367",
            name: "Pistachio Green Dk",
            red: 97,
            green: 122,
            blue: 82,
        },
        Floss {
            number: "319",
            name: "Pistachio Grn Vy Dk",
            red: 32,
            green: 95,
            blue: 46,
        },
        Floss {
            number: "890",
            name: "Pistachio Grn Ult V D",
            red: 23,
            green: 73,
            blue: 35,
        },
        Floss {
            number: "164",
            name: "Forest Green Lt",
            red: 200,
            green: 216,
            blue: 184,
        },
        Floss {
            number: "989",
            name: "Forest Green ",
            red: 141,
            green: 166,
            blue: 117,
        },
        Floss {
            number: "988",
            name: "Forest Green Med",
            red: 115,
            green: 139,
            blue: 91,
        },
        Floss {
            number: "987",
            name: "Forest Green Dk",
            red: 88,
            green: 113,
            blue: 65,
        },
        Floss {
            number: "986",
            name: "Forest Green Vy Dk",
            red: 64,
            green: 82,
            blue: 48,
        },
        Floss {
            number: "772",
            name: "Yellow Green Vy Lt",
            red: 228,
            green: 236,
            blue: 212,
        },
        Floss {
            number: "3348",
            name: "Yellow Green Lt",
            red: 204,
            green: 217,
            blue: 177,
        },
        Floss {
            number: "3347",
            name: "Yellow Green Med",
            red: 113,
            green: 147,
            blue: 92,
        },
        Floss {
            number: "3346",
            name: "Hunter Green",
            red: 64,
            green: 106,
            blue: 58,
        },
        Floss {
            number: "3345",
            name: "Hunter Green Dk",
            red: 27,
            green: 89,
            blue: 21,
        },
        Floss {
            number: "895",
            name: "Hunter Green Vy Dk",
            red: 27,
            green: 83,
            blue: 0,
        },
        Floss {
            number: "704",
            name: "Chartreuse Bright",
            red: 158,
            green: 207,
            blue: 52,
        },
        Floss {
            number: "703",
            name: "Chartreuse",
            red: 123,
            green: 181,
            blue: 71,
        },
        Floss {
            number: "702",
            name: "Kelly Green",
            red: 71,
            green: 167,
            blue: 47,
        },
        Floss {
            number: "701",
            name: "Green Light",
            red: 63,
            green: 143,
            blue: 41,
        },
        Floss {
            number: "700",
            name: "Green Bright",
            red: 7,
            green: 115,
            blue: 27,
        },
        Floss {
            number: "699",
            name: "Green",
            red: 5,
            green: 101,
            blue: 23,
        },
        Floss {
            number: "907",
            name: "Parrot Green Lt",
            red: 199,
            green: 230,
            blue: 102,
        },
        Floss {
            number: "906",
            name: "Parrot Green Md",
            red: 127,
            green: 179,
            blue: 53,
        },
        Floss {
            number: "905",
            name: "Parrot Green Dk",
            red: 98,
            green: 138,
            blue: 40,
        },
        Floss {
            number: "904",
            name: "Parrot Green V Dk",
            red: 85,
            green: 120,
            blue: 34,
        },
        Floss {
            number: "472",
            name: "Avocado Grn U Lt",
            red: 216,
            green: 228,
            blue: 152,
        },
        Floss {
            number: "471",
            name: "Avocado Grn V Lt",
            red: 174,
            green: 191,
            blue: 121,
        },
        Floss {
            number: "470",
            name: "Avocado Grn Lt",
            red: 148,
            green: 171,
            blue: 79,
        },
        Floss {
            number: "469",
            name: "Avocado Green",
            red: 114,
            green: 132,
            blue: 60,
        },
        Floss {
            number: "937",
            name: "Avocado Green Md",
            red: 98,
            green: 113,
            blue: 51,
        },
        Floss {
            number: "936",
            name: "Avocado Grn V Dk",
            red: 76,
            green: 88,
            blue: 38,
        },
        Floss {
            number: "935",
            name: "Avocado Green Dk",
            red: 66,
            green: 77,
            blue: 33,
        },
        Floss {
            number: "934",
            name: "Avocado Grn Black",
            red: 49,
            green: 57,
            blue: 25,
        },
        Floss {
            number: "523",
            name: "Fern Green Lt",
            red: 171,
            green: 177,
            blue: 151,
        },
        Floss {
            number: "3053",
            name: "Green Gray",
            red: 156,
            green: 164,
            blue: 130,
        },
        Floss {
            number: "3052",
            name: "Green Gray Md",
            red: 136,
            green: 146,
            blue: 104,
        },
        Floss {
            number: "3051",
            name: "Green Gray Dk",
            red: 95,
            green: 102,
            blue: 72,
        },
        Floss {
            number: "524",
            name: "Fern Green Vy Lt",
            red: 196,
            green: 205,
            blue: 172,
        },
        Floss {
            number: "522",
            name: "Fern Green",
            red: 150,
            green: 158,
            blue: 126,
        },
        Floss {
            number: "520",
            name: "Fern Green Dark",
            red: 102,
            green: 109,
            blue: 79,
        },
        Floss {
            number: "3364",
            name: "Pine Green",
            red: 131,
            green: 151,
            blue: 95,
        },
        Floss {
            number: "3363",
            name: "Pine Green Md",
            red: 114,
            green: 130,
            blue: 86,
        },
        Floss {
            number: "3362",
            name: "Pine Green Dk",
            red: 94,
            green: 107,
            blue: 71,
        },
        Floss {
            number: "165",
            name: "Moss Green Vy Lt",
            red: 239,
            green: 244,
            blue: 164,
        },
        Floss {
            number: "3819",
            name: "Moss Green Lt",
            red: 224,
            green: 232,
            blue: 104,
        },
        Floss {
            number: "166",
            name: "Moss Green Md Lt",
            red: 192,
            green: 200,
            blue: 64,
        },
        Floss {
            number: "581",
            name: "Moss Green",
            red: 167,
            green: 174,
            blue: 56,
        },
        Floss {
            number: "580",
            name: "Moss Green Dk",
            red: 136,
            green: 141,
            blue: 51,
        },
        Floss {
            number: "734",
            name: "Olive Green Lt",
            red: 199,
            green: 192,
            blue: 119,
        },
        Floss {
            number: "733",
            name: "Olive Green Md",
            red: 188,
            green: 179,
            blue: 76,
        },
        Floss {
            number: "732",
            name: "Olive Green",
            red: 148,
            green: 140,
            blue: 54,
        },
        Floss {
            number: "731",
            name: "Olive Green Dk",
            red: 147,
            green: 139,
            blue: 55,
        },
        Floss {
            number: "730",
            name: "Olive Green V Dk",
            red: 130,
            green: 123,
            blue: 48,
        },
        Floss {
            number: "3013",
            name: "Khaki Green Lt",
            red: 185,
            green: 185,
            blue: 130,
        },
        Floss {
            number: "3012",
            name: "Khaki Green Md",
            red: 166,
            green: 167,
            blue: 93,
        },
        Floss {
            number: "3011",
            name: "Khaki Green Dk",
            red: 137,
            green: 138,
            blue: 88,
        },
        Floss {
            number: "372",
            name: "Mustard Lt",
            red: 204,
            green: 183,
            blue: 132,
        },
        Floss {
            number: "371",
            name: "Mustard",
            red: 191,
            green: 166,
            blue: 113,
        },
        Floss {
            number: "370",
            name: "Mustard Medium",
            red: 184,
            green: 157,
            blue: 100,
        },
        Floss {
            number: "834",
            name: "Golden Olive Vy Lt",
            red: 219,
            green: 190,
            blue: 127,
        },
        Floss {
            number: "833",
            name: "Golden Olive Lt",
            red: 200,
            green: 171,
            blue: 108,
        },
        Floss {
            number: "832",
            name: "Golden Olive",
            red: 189,
            green: 155,
            blue: 81,
        },
        Floss {
            number: "831",
            name: "Golden Olive Md",
            red: 170,
            green: 143,
            blue: 86,
        },
        Floss {
            number: "830",
            name: "Golden Olive Dk",
            red: 141,
            green: 120,
            blue: 75,
        },
        Floss {
            number: "829",
            name: "Golden Olive Vy Dk",
            red: 126,
            green: 107,
            blue: 66,
        },
        Floss {
            number: "613",
            name: "Drab Brown V Lt",
            red: 220,
            green: 196,
            blue: 170,
        },
        Floss {
            number: "612",
            name: "Drab Brown Lt",
            red: 188,
            green: 154,
            blue: 120,
        },
        Floss {
            number: "611",
            name: "Drab Brown",
            red: 150,
            green: 118,
            blue: 86,
        },
        Floss {
            number: "610",
            name: "Drab Brown Dk",
            red: 121,
            green: 96,
            blue: 71,
        },
        Floss {
            number: "3047",
            name: "Yellow Beige Lt",
            red: 231,
            green: 214,
            blue: 193,
        },
        Floss {
            number: "3046",
            name: "Yellow Beige Md",
            red: 216,
            green: 188,
            blue: 154,
        },
        Floss {
            number: "3045",
            name: "Yellow Beige Dk",
            red: 188,
            green: 150,
            blue: 106,
        },
        Floss {
            number: "167",
            name: "Yellow Beige V Dk",
            red: 167,
            green: 124,
            blue: 73,
        },
        Floss {
            number: "746",
            name: "Off White",
            red: 252,
            green: 252,
            blue: 238,
        },
        Floss {
            number: "677",
            name: "Old Gold Vy Lt",
            red: 245,
            green: 236,
            blue: 203,
        },
        Floss {
            number: "422",
            name: "Hazelnut Brown Lt",
            red: 198,
            green: 159,
            blue: 123,
        },
        Floss {
            number: "3828",
            name: "Hazelnut Brown",
            red: 183,
            green: 139,
            blue: 97,
        },
        Floss {
            number: "420",
            name: "Hazelnut Brown Dk",
            red: 160,
            green: 112,
            blue: 66,
        },
        Floss {
            number: "869",
            name: "Hazelnut Brown V Dk",
            red: 131,
            green: 94,
            blue: 57,
        },
        Floss {
            number: "728",
            name: "Topaz",
            red: 228,
            green: 180,
            blue: 104,
        },
        Floss {
            number: "783",
            name: "Topaz Medium",
            red: 206,
            green: 145,
            blue: 36,
        },
        Floss {
            number: "782",
            name: "Topaz Dark",
            red: 174,
            green: 119,
            blue: 32,
        },
        Floss {
            number: "781",
            name: "Topaz Very Dark",
            red: 162,
            green: 109,
            blue: 32,
        },
        Floss {
            number: "780",
            name: "Topaz Ultra Vy Dk",
            red: 148,
            green: 99,
            blue: 26,
        },
        Floss {
            number: "676",
            name: "Old Gold Lt",
            red: 229,
            green: 206,
            blue: 151,
        },
        Floss {
            number: "729",
            name: "Old Gold Medium",
            red: 208,
            green: 165,
            blue: 62,
        },
        Floss {
            number: "680",
            name: "Old Gold Dark",
            red: 188,
            green: 141,
            blue: 14,
        },
        Floss {
            number: "3829",
            name: "Old Gold Vy Dark",
            red: 169,
            green: 130,
            blue: 4,
        },
        Floss {
            number: "3822",
            name: "Straw Light",
            red: 246,
            green: 220,
            blue: 152,
        },
        Floss {
            number: "3821",
            name: "Straw",
            red: 243,
            green: 206,
            blue: 117,
        },
        Floss {
            number: "3820",
            name: "Straw Dark",
            red: 223,
            green: 182,
            blue: 95,
        },
        Floss {
            number: "3852",
            name: "Straw Very Dark",
            red: 205,
            green: 157,
            blue: 55,
        },
        Floss {
            number: "445",
            name: "Lemon Light",
            red: 255,
            green: 251,
            blue: 139,
        },
        Floss {
            number: "307",
            name: "Lemon",
            red: 253,
            green: 237,
            blue: 84,
        },
        Floss {
            number: "973",
            name: "Canary Bright",
            red: 255,
            green: 227,
            blue: 0,
        },
        Floss {
            number: "444",
            name: "Lemon Dark",
            red: 255,
            green: 214,
            blue: 0,
        },
        Floss {
            number: "3078",
            name: "Golden Yellow Vy Lt",
            red: 253,
            green: 249,
            blue: 205,
        },
        Floss {
            number: "727",
            name: "Topaz Vy Lt",
            red: 255,
            green: 241,
            blue: 175,
        },
        Floss {
            number: "726",
            name: "Topaz Light",
            red: 253,
            green: 215,
            blue: 85,
        },
        Floss {
            number: "725",
            name: "Topaz Med Lt",
            red: 255,
            green: 200,
            blue: 64,
        },
        Floss {
            number: "972",
            name: "Canary Deep",
            red: 255,
            green: 181,
            blue: 21,
        },
        Floss {
            number: "745",
            name: "Yellow Pale Light",
            red: 255,
            green: 233,
            blue: 173,
        },
        Floss {
            number: "744",
            name: "Yellow Pale",
            red: 255,
            green: 231,
            blue: 147,
        },
        Floss {
            number: "743",
            name: "Yellow Med",
            red: 254,
            green: 211,
            blue: 118,
        },
        Floss {
            number: "742",
            name: "Tangerine Light",
            red: 255,
            green: 191,
            blue: 87,
        },
        Floss {
            number: "741",
            name: "Tangerine Med",
            red: 255,
            green: 163,
            blue: 43,
        },
        Floss {
            number: "740",
            name: "Tangerine",
            red: 255,
            green: 139,
            blue: 0,
        },
        Floss {
            number: "970",
            name: "Pumpkin Light",
            red: 247,
            green: 139,
            blue: 19,
        },
        Floss {
            number: "971",
            name: "Pumpkin",
            red: 246,
            green: 127,
            blue: 0,
        },
        Floss {
            number: "947",
            name: "Burnt Orange",
            red: 255,
            green: 123,
            blue: 77,
        },
        Floss {
            number: "946",
            name: "Burnt Orange Med",
            red: 235,
            green: 99,
            blue: 7,
        },
        Floss {
            number: "900",
            name: "Burnt Orange Dark",
            red: 209,
            green: 88,
            blue: 7,
        },
        Floss {
            number: "967",
            name: "Apricot Very Light",
            red: 255,
            green: 222,
            blue: 213,
        },
        Floss {
            number: "3824",
            name: "Apricot Light",
            red: 254,
            green: 205,
            blue: 194,
        },
        Floss {
            number: "3341",
            name: "Apricot",
            red: 252,
            green: 171,
            blue: 152,
        },
        Floss {
            number: "3340",
            name: "Apricot Med",
            red: 255,
            green: 131,
            blue: 111,
        },
        Floss {
            number: "608",
            name: "Burnt Orange Bright",
            red: 253,
            green: 93,
            blue: 53,
        },
        Floss {
            number: "606",
            name: "Orange?Red Bright",
            red: 250,
            green: 50,
            blue: 3,
        },
        Floss {
            number: "951",
            name: "Tawny Light",
            red: 255,
            green: 226,
            blue: 207,
        },
        Floss {
            number: "3856",
            name: "Mahogany Ult Vy Lt",
            red: 255,
            green: 211,
            blue: 181,
        },
        Floss {
            number: "722",
            name: "Orange Spice Light",
            red: 247,
            green: 151,
            blue: 111,
        },
        Floss {
            number: "721",
            name: "Orange Spice Med",
            red: 242,
            green: 120,
            blue: 66,
        },
        Floss {
            number: "720",
            name: "Orange Spice Dark",
            red: 229,
            green: 92,
            blue: 31,
        },
        Floss {
            number: "3825",
            name: "Pumpkin Pale",
            red: 253,
            green: 189,
            blue: 150,
        },
        Floss {
            number: "922",
            name: "Copper Light",
            red: 226,
            green: 115,
            blue: 35,
        },
        Floss {
            number: "921",
            name: "Copper",
            red: 198,
            green: 98,
            blue: 24,
        },
        Floss {
            number: "920",
            name: "Copper Med",
            red: 172,
            green: 84,
            blue: 20,
        },
        Floss {
            number: "919",
            name: "Red?Copper",
            red: 166,
            green: 69,
            blue: 16,
        },
        Floss {
            number: "918",
            name: "Red?Copper Dark",
            red: 130,
            green: 52,
            blue: 10,
        },
        Floss {
            number: "3770",
            name: "Tawny Vy Light",
            red: 255,
            green: 238,
            blue: 227,
        },
        Floss {
            number: "945",
            name: "Tawny",
            red: 251,
            green: 213,
            blue: 187,
        },
        Floss {
            number: "402",
            name: "Mahogany Vy Lt",
            red: 247,
            green: 167,
            blue: 119,
        },
        Floss {
            number: "3776",
            name: "Mahogany Light",
            red: 207,
            green: 121,
            blue: 57,
        },
        Floss {
            number: "301",
            name: "Mahogany Med",
            red: 179,
            green: 95,
            blue: 43,
        },
        Floss {
            number: "400",
            name: "Mahogany Dark",
            red: 143,
            green: 67,
            blue: 15,
        },
        Floss {
            number: "300",
            name: "Mahogany Vy Dk",
            red: 111,
            green: 47,
            blue: 0,
        },
        Floss {
            number: "3823",
            name: "Yellow Ultra Pale",
            red: 255,
            green: 253,
            blue: 227,
        },
        Floss {
            number: "3855",
            name: "Autumn Gold Lt",
            red: 250,
            green: 211,
            blue: 150,
        },
        Floss {
            number: "3854",
            name: "Autumn Gold Med",
            red: 242,
            green: 175,
            blue: 104,
        },
        Floss {
            number: "3853",
            name: "Autumn Gold Dk",
            red: 242,
            green: 151,
            blue: 70,
        },
        Floss {
            number: "3827",
            name: "Golden Brown Pale",
            red: 247,
            green: 187,
            blue: 119,
        },
        Floss {
            number: "977",
            name: "Golden Brown Light",
            red: 220,
            green: 156,
            blue: 86,
        },
        Floss {
            number: "976",
            name: "Golden Brown Med",
            red: 194,
            green: 129,
            blue: 66,
        },
        Floss {
            number: "3826",
            name: "Golden Brown",
            red: 173,
            green: 114,
            blue: 57,
        },
        Floss {
            number: "975",
            name: "Golden Brown Dk",
            red: 145,
            green: 79,
            blue: 18,
        },
        Floss {
            number: "948",
            name: "Peach Very Light",
            red: 254,
            green: 231,
            blue: 218,
        },
        Floss {
            number: "754",
            name: "Peach Light",
            red: 247,
            green: 203,
            blue: 191,
        },
        Floss {
            number: "3771",
            name: "Terra Cotta Ult Vy Lt",
            red: 244,
            green: 187,
            blue: 169,
        },
        Floss {
            number: "758",
            name: "Terra Cotta Vy Lt",
            red: 238,
            green: 170,
            blue: 155,
        },
        Floss {
            number: "3778",
            name: "Terra Cotta Light",
            red: 217,
            green: 137,
            blue: 120,
        },
        Floss {
            number: "356",
            name: "Terra Cotta Med",
            red: 197,
            green: 106,
            blue: 91,
        },
        Floss {
            number: "3830",
            name: "Terra Cotta",
            red: 185,
            green: 85,
            blue: 68,
        },
        Floss {
            number: "355",
            name: "Terra Cotta Dark",
            red: 152,
            green: 68,
            blue: 54,
        },
        Floss {
            number: "3777",
            name: "Terra Cotta Vy Dk",
            red: 134,
            green: 48,
            blue: 34,
        },
        Floss {
            number: "3779",
            name: "Rosewood Ult Vy Lt",
            red: 248,
            green: 202,
            blue: 200,
        },
        Floss {
            number: "3859",
            name: "Rosewood Light",
            red: 186,
            green: 139,
            blue: 124,
        },
        Floss {
            number: "3858",
            name: "Rosewood Med",
            red: 150,
            green: 74,
            blue: 63,
        },
        Floss {
            number: "3857",
            name: "Rosewood Dark",
            red: 104,
            green: 37,
            blue: 26,
        },
        Floss {
            number: "3774",
            name: "Desert Sand Vy Lt",
            red: 243,
            green: 225,
            blue: 215,
        },
        Floss {
            number: "950",
            name: "Desert Sand Light",
            red: 238,
            green: 211,
            blue: 196,
        },
        Floss {
            number: "3064",
            name: "Desert Sand",
            red: 196,
            green: 142,
            blue: 112,
        },
        Floss {
            number: "407",
            name: "Desert Sand Med",
            red: 187,
            green: 129,
            blue: 97,
        },
        Floss {
            number: "3773",
            name: "Desert Sand Dark",
            red: 182,
            green: 117,
            blue: 82,
        },
        Floss {
            number: "3772",
            name: "Desert Sand Vy Dk",
            red: 160,
            green: 108,
            blue: 80,
        },
        Floss {
            number: "632",
            name: "Desert Sand Ult Vy Dk",
            red: 135,
            green: 85,
            blue: 57,
        },
        Floss {
            number: "453",
            name: "Shell Gray Light",
            red: 215,
            green: 206,
            blue: 203,
        },
        Floss {
            number: "452",
            name: "Shell Gray Med",
            red: 192,
            green: 179,
            blue: 174,
        },
        Floss {
            number: "451",
            name: "Shell Gray Dark",
            red: 145,
            green: 123,
            blue: 115,
        },
        Floss {
            number: "3861",
            name: "Cocoa Light",
            red: 166,
            green: 136,
            blue: 129,
        },
        Floss {
            number: "3860",
            name: "Cocoa",
            red: 125,
            green: 93,
            blue: 87,
        },
        Floss {
            number: "779",
            name: "Cocoa Dark",
            red: 98,
            green: 75,
            blue: 69,
        },
        Floss {
            number: "712",
            name: "Cream",
            red: 255,
            green: 251,
            blue: 239,
        },
        Floss {
            number: "739",
            name: "Tan Ult Vy Lt",
            red: 248,
            green: 228,
            blue: 200,
        },
        Floss {
            number: "738",
            name: "Tan Very Light",
            red: 236,
            green: 204,
            blue: 158,
        },
        Floss {
            number: "437",
            name: "Tan Light",
            red: 228,
            green: 187,
            blue: 142,
        },
        Floss {
            number: "436",
            name: "Tan",
            red: 203,
            green: 144,
            blue: 81,
        },
        Floss {
            number: "435",
            name: "Brown Very Light",
            red: 184,
            green: 119,
            blue: 72,
        },
        Floss {
            number: "434",
            name: "Brown Light",
            red: 152,
            green: 94,
            blue: 51,
        },
        Floss {
            number: "433",
            name: "Brown Med",
            red: 122,
            green: 69,
            blue: 31,
        },
        Floss {
            number: "801",
            name: "Coffee Brown Dk",
            red: 101,
            green: 57,
            blue: 25,
        },
        Floss {
            number: "898",
            name: "Coffee Brown Vy Dk",
            red: 73,
            green: 42,
            blue: 19,
        },
        Floss {
            number: "938",
            name: "Coffee Brown Ult Dk",
            red: 54,
            green: 31,
            blue: 14,
        },
        Floss {
            number: "3371",
            name: "Black Brown",
            red: 30,
            green: 17,
            blue: 8,
        },
        Floss {
            number: "543",
            name: "Beige Brown Ult Vy Lt",
            red: 242,
            green: 227,
            blue: 206,
        },
        Floss {
            number: "3864",
            name: "Mocha Beige Light",
            red: 203,
            green: 182,
            blue: 156,
        },
        Floss {
            number: "3863",
            name: "Mocha Beige Med",
            red: 164,
            green: 131,
            blue: 92,
        },
        Floss {
            number: "3862",
            name: "Mocha Beige Dark",
            red: 138,
            green: 110,
            blue: 78,
        },
        Floss {
            number: "3031",
            name: "Mocha Brown Vy Dk",
            red: 75,
            green: 60,
            blue: 42,
        },
        Floss {
            number: "B5200",
            name: "Snow White",
            red: 255,
            green: 255,
            blue: 255,
        },
        Floss {
            number: "White",
            name: "White",
            red: 252,
            green: 251,
            blue: 248,
        },
        Floss {
            number: "3865",
            name: "Winter White",
            red: 249,
            green: 247,
            blue: 241,
        },
        Floss {
            number: "Ecru",
            name: "Ecru",
            red: 240,
            green: 234,
            blue: 218,
        },
        Floss {
            number: "822",
            name: "Beige Gray Light",
            red: 231,
            green: 226,
            blue: 211,
        },
        Floss {
            number: "644",
            name: "Beige Gray Med",
            red: 221,
            green: 216,
            blue: 203,
        },
        Floss {
            number: "642",
            name: "Beige Gray Dark",
            red: 164,
            green: 152,
            blue: 120,
        },
        Floss {
            number: "640",
            name: "Beige Gray Vy Dk",
            red: 133,
            green: 123,
            blue: 97,
        },
        Floss {
            number: "3787",
            name: "Brown Gray Dark",
            red: 98,
            green: 93,
            blue: 80,
        },
        Floss {
            number: "3021",
            name: "Brown Gray Vy Dk",
            red: 79,
            green: 75,
            blue: 65,
        },
        Floss {
            number: "3024",
            name: "Brown Gray Vy Lt",
            red: 235,
            green: 234,
            blue: 231,
        },
        Floss {
            number: "3023",
            name: "Brown Gray Light",
            red: 177,
            green: 170,
            blue: 151,
        },
        Floss {
            number: "3022",
            name: "Brown Gray Med",
            red: 142,
            green: 144,
            blue: 120,
        },
        Floss {
            number: "535",
            name: "Ash Gray Vy Lt",
            red: 99,
            green: 100,
            blue: 88,
        },
        Floss {
            number: "3033",
            name: "Mocha Brown Vy Lt",
            red: 227,
            green: 216,
            blue: 204,
        },
        Floss {
            number: "3782",
            name: "Mocha Brown Lt",
            red: 210,
            green: 188,
            blue: 166,
        },
        Floss {
            number: "3032",
            name: "Mocha Brown Med",
            red: 179,
            green: 159,
            blue: 139,
        },
        Floss {
            number: "3790",
            name: "Beige Gray Ult Dk",
            red: 127,
            green: 106,
            blue: 85,
        },
        Floss {
            number: "3781",
            name: "Mocha Brown Dk",
            red: 107,
            green: 87,
            blue: 67,
        },
        Floss {
            number: "3866",
            name: "Mocha Brn Ult Vy Lt",
            red: 250,
            green: 246,
            blue: 240,
        },
        Floss {
            number: "842",
            name: "Beige Brown Vy Lt",
            red: 209,
            green: 186,
            blue: 161,
        },
        Floss {
            number: "841",
            name: "Beige Brown Lt",
            red: 182,
            green: 155,
            blue: 126,
        },
        Floss {
            number: "840",
            name: "Beige Brown Med",
            red: 154,
            green: 124,
            blue: 92,
        },
        Floss {
            number: "839",
            name: "Beige Brown Dk",
            red: 103,
            green: 85,
            blue: 65,
        },
        Floss {
            number: "838",
            name: "Beige Brown Vy Dk",
            red: 89,
            green: 73,
            blue: 55,
        },
        Floss {
            number: "3072",
            name: "Beaver Gray Vy Lt",
            red: 230,
            green: 232,
            blue: 232,
        },
        Floss {
            number: "648",
            name: "Beaver Gray Lt",
            red: 188,
            green: 180,
            blue: 172,
        },
        Floss {
            number: "647",
            name: "Beaver Gray Med",
            red: 176,
            green: 166,
            blue: 156,
        },
        Floss {
            number: "646",
            name: "Beaver Gray Dk",
            red: 135,
            green: 125,
            blue: 115,
        },
        Floss {
            number: "645",
            name: "Beaver Gray Vy Dk",
            red: 110,
            green: 101,
            blue: 92,
        },
        Floss {
            number: "844",
            name: "Beaver Gray Ult Dk",
            red: 72,
            green: 72,
            blue: 72,
        },
        Floss {
            number: "762",
            name: "Pearl Gray Vy Lt",
            red: 236,
            green: 236,
            blue: 236,
        },
        Floss {
            number: "415",
            name: "Pearl Gray",
            red: 211,
            green: 211,
            blue: 214,
        },
        Floss {
            number: "318",
            name: "Steel Gray Lt",
            red: 171,
            green: 171,
            blue: 171,
        },
        Floss {
            number: "414",
            name: "Steel Gray Dk",
            red: 140,
            green: 140,
            blue: 140,
        },
        Floss {
            number: "168",
            name: "Pewter Very Light",
            red: 209,
            green: 209,
            blue: 209,
        },
        Floss {
            number: "169",
            name: "Pewter Light",
            red: 132,
            green: 132,
            blue: 132,
        },
        Floss {
            number: "317",
            name: "Pewter Gray",
            red: 108,
            green: 108,
            blue: 108,
        },
        Floss {
            number: "413",
            name: "Pewter Gray Dark",
            red: 86,
            green: 86,
            blue: 86,
        },
        Floss {
            number: "3799",
            name: "Pewter Gray Vy Dk",
            red: 66,
            green: 66,
            blue: 66,
        },
        Floss {
            number: "310",
            name: "Black",
            red: 0,
            green: 0,
            blue: 0,
        },
    ]
}
